diff_type: "sde"
init_unet_ckpt: "/home/user/data4/diffusion/defensediffusion/tinyimagenet_sde/score_sde/checkpoint_200000.pth"
other_config: "./configs/vp_sde_tiny.yaml"    # including model, training recipe, etc.

cls_version: "pang_tiny_wrn-28-10-swish"
resnet_ckpt: "/home/user/data4/diffusion/DiffPure/cls_model/tinyimagenet_w28_aa/checkpoint_best.pth"
tune_T: 0.2
eps: 8

output_dir: "/home/user/data4/diffusion/defensediffusion/tinyimagenet_sde/ft_fz_wcls_w28/"

dataset: "TinyImageNet"
centered: True


advtrain: True

log_freq: 100
snapshot_freq: 5000
total_iterations: 30000

fix_t: True
fix_z: True
with_cls: True


