diff_type: "sde"
init_unet_ckpt: "/home/user/data4/diffusion/defensediffusion/imagenet100_sde/score_sde/checkpoint_200000.pth"
other_config: "./configs/vp_sde_imagenet100.yaml"    # including model, training recipe, etc.

cls_version: "vanilla_r50"
resnet_ckpt: "torchvision"
tune_T: 0.2
eps: 8

output_dir: "/home/user/data4/diffusion/defensediffusion/imagenet100_sde/ft_fz_wcls_r50_2/"

dataset: "ImageNet100"
centered: True


advtrain: True

log_freq: 100
snapshot_freq: 5000
total_iterations: 30000

fix_t: True
fix_z: True
with_cls: True


